---

  - name: Tomcat-Webapps-Deploy-apiANDtest
    hosts: tomcat-api
    remote_user: root

  - name: tomcat-service-stop
    hosts: tomcat-api
    tasks:
      - shell: tomcat_ctl stop

  - name: tomcat-warAndDir-bakup
    hosts: tomcat-api
    tasks:
      - shell: tomcat_ctl bakup

  - name: test-war-copy
    hosts: tomcat-api
    remote_user: root
    tasks:
      - copy: src=/data/script/test.war dest=/opt/tomcat_test/webapps/test.war owner=somp group=somp mode=755

  - name: api-war-copy
    hosts: tomcat-api
    remote_user: root
    tasks:
      - copy: src=/data/script/testapi.war dest=/opt/tomcat/webapps/testapi.war owner=somp group=somp mode=755

  - name: tomcat-service-start
      hosts: tomcat-api
      remote_user: root
      tasks:
        - command: echo hello
          notify: restart tomcat