#!/bin/bash
# description: Tomcat7 Start Stop Restart
# processname: tomcat7
# 执行用户为somp
# chkconfig: 234 20 80

# 获取系统当前时间并设置为变量
DATE=`date +%Y%m%d-%H%M%S`

# 获取当前tomcat进程
TPID=`ps aux|grep tomcat|grep Xms|grep tomcat/bin|awk  '{print $2}'`

# 环境变量需要根据自己jdk的安装位置进行配置

JAVA_HOME=/opt/jdk
JRE_HOME=$JAVA_HOME/jre
CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar
PATH=$JAVA_HOME/bin:$JRE_HOME/bin:$PATH
export JAVA_HOME JRE_HOME CLASSPATH PATH

# 根据自己安装tomcat的位置进行配置
CATALINA_HOME=/opt/tomcat
#CATALINA_HOME_END=/opt/tomcat_end - 如果多个tomcat可以通过如此进行批量控制 但不建议如此 耦合性太高

case $1 in
start)
su - somp -c "sh $CATALINA_HOME/bin/startup.sh"
;;
stop)
kill -9 $TPID  && echo "tomcat shutdown OK"
;;
restart)
kill -9 $TPID  && echo "tomcat shutdown OK"
su - somp -c "sh $CATALINA_HOME/bin/startup.sh"
;;
backup)
mkdir -p /data/script/tomcat/$DATE && cp -r /opt/tomcat/webapps/* /data/script/tomcat/$DATE
;;
esac
exit 0